import { useEffect, useState } from 'react';
import { getLearning, saveLearning, toggleLearning, type LearningState } from '../lib/learning';
export default function LearningTools({ id }: { id: string }) {
  const [state, setState] = useState<LearningState>({ saved: [], read: [], notes: {} });
  const [message, setMessage] = useState('Your notes stay in this browser.');
  useEffect(() => { const sync = () => setState({ ...getLearning() }); sync(); window.addEventListener('learning-change', sync); window.addEventListener('storage', sync); return () => { window.removeEventListener('learning-change', sync); window.removeEventListener('storage', sync); }; }, []);
  function toggle(kind: 'saved' | 'read') { setMessage(toggleLearning(kind, id) ? 'Updated in this browser.' : 'Storage unavailable. Changes last for this page session.'); }
  return <div className="learning-tools"><div className="flex flex-wrap gap-3"><button className="button secondary" aria-pressed={state.saved.includes(id)} onClick={() => toggle('saved')}>{state.saved.includes(id) ? '✓ Saved to your collection' : '＋ Save for later'}</button><button className="button secondary" aria-pressed={state.read.includes(id)} onClick={() => toggle('read')}>{state.read.includes(id) ? '✓ Marked as read' : '○ Mark as read'}</button></div><details className="mt-4"><summary className="cursor-pointer text-sm text-muted">Your notebook ↗</summary><label className="mt-4 block text-sm" htmlFor={`notes-${id}`}>What surprised you? What would you like to investigate?</label><textarea id={`notes-${id}`} className="note-input" rows={4} value={state.notes[id] || ''} placeholder="Make the idea your own…" onChange={e => { const next = { ...getLearning(), notes: { ...getLearning().notes, [id]: e.target.value } }; setState(next); setMessage(saveLearning(next) ? 'Note saved in this browser.' : 'Storage unavailable. Copy your note before leaving.'); }} /></details><p className="mt-2 text-xs text-faint" role="status">{message}</p></div>;
}
