import {useEffect,useRef,useState} from 'react';
import {harmonicWeights,pairForce,pairPotential,waveValue,wavelength} from '../lib/matter-sound';
function useMotion(){
 const [running,setRunning]=useState(false),[phase,setPhase]=useState(0);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setRunning(!q.matches);change();q.addEventListener('change',change);return()=>q.removeEventListener('change',change);},[]);
 useEffect(()=>{if(!running)return;let frame=0,last=0;const tick=(now:number)=>{if(last&&!document.hidden)setPhase(p=>(p+Math.min(now-last,50)/1000)%(Math.PI*100));last=now;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[running]);
 return {running,setRunning,phase,setPhase};
}
const steps=[
 ['01 · Everyday contact','Your hand and a table deform slightly at contact. Bonds between atoms transmit a restoring force through the materials. A surface is not a set of impenetrable microscopic billiard balls.'],
 ['02 · Electromagnetic interactions','Nuclei and electrons attract and repel electrically. When atoms are brought too close, the total energy rises steeply. Electron clouds are probability distributions, not hollow shells with paths between them.'],
 ['03 · Quantum structure','Electrons are fermions: the full many-electron state must respect the Pauli exclusion principle. Overlapping occupied states changes the allowed states and energy. This acts together with electromagnetic interactions; exclusion is not a separate classical push.'],
];
export function MatterLab(){
 const [separation,setSeparation]=useState(1.55),[step,setStep]=useState(0),[clouds,setClouds]=useState(true);
 const {running,setRunning,phase}=useMotion();
 const right=240+separation*90,force=pairForce(separation),repulsive=force>0;
 const path=Array.from({length:141},(_,i)=>{const r=.96+i*1.64/140;return `${i?'L':'M'}${45+i*4.7},${210-Math.max(-1.1,Math.min(3,pairPotential(r)))*40}`;}).join(' ');
 const markerX=45+(separation-.96)/1.64*658,markerY=210-Math.max(-1.1,Math.min(3,pairPotential(separation)))*40;
 return <div className="sensory-lab" data-testid="matter-lab"><div className="lab-toolbar"><span className="eyebrow">MATTER / A CONCEPTUAL ZOOM</span><button className="button" onClick={()=>setRunning(!running)}>{running?'Pause motion':'Resume motion'}</button></div>
 <div className="narration-steps" role="group" aria-label="Explanation stage">{steps.map(([name],i)=><button key={name} aria-pressed={step===i} onClick={()=>setStep(i)}>{name}</button>)}</div><p className="stage-copy" aria-live="polite">{steps[step][1]}</p>
 <svg viewBox="0 0 760 310" role="img" aria-label="Two simplified solid surfaces. Moving them closer increases overlap of their electron distributions and raises the model energy." className="particle-view">
 <text x="65" y="32">LEFT SOLID</text><text x="515" y="32">RIGHT SOLID</text>
 {[0,1].flatMap(side=>Array.from({length:9},(_,i)=>{const col=i%3,row=Math.floor(i/3),x=(side?right:60)+col*90,y=90+row*75,jiggle=running?Math.sin(phase*3+i)*1.4:0;return <g key={`${side}-${i}`}><circle cx={x+jiggle} cy={y} r="49" fill={side?'var(--tk-sim-warm)':'var(--tk-sim-cool)'} opacity={clouds?.15:0}/><circle cx={x+jiggle} cy={y} r="5" fill={side?'var(--tk-sim-warm)':'var(--tk-sim-cool)'}/></g>;}))}
 <path d={`M245 285 H${right-5}`} stroke="var(--tk-sim-ink)"/><text x={(245+right)/2} y="273" textAnchor="middle">r</text>
 </svg>
 <p className="particle-caption">Blue: left solid · Gold: right solid · Discs: schematic electron distributions. Sizes and motion are exaggerated.</p>
 <div className="sensory-controls"><label>Surface separation · {separation.toFixed(2)} σ<input aria-label="Surface separation" type="range" min="0.96" max="2.6" step="0.01" value={separation} onChange={e=>setSeparation(+e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={clouds} onChange={e=>setClouds(e.target.checked)}/> Show electron distributions</label></div>
 <div className="lab-readout" role="status"><strong>{Math.abs(separation-2**(1/6))<.005?'Near balance':repulsive?'Repulsive region':'Attractive region'}</strong><span>{repulsive?'Push closer: the energy cost climbs rapidly.':'At larger separation, the illustrative pair interaction is weakly attractive.'}</span></div>
 <details className="model-details"><summary>See the energy curve & model limits</summary><svg className="particle-view energy-view" viewBox="0 0 760 290" role="img" aria-label="Dimensionless Lennard-Jones potential: a shallow attractive well followed by a steep rise at close separation."><path d="M45 50V260H720 M45 210H720" fill="none" stroke="var(--tk-sim-muted)"/><path d={path} fill="none" stroke="var(--tk-sim-cool)" strokeWidth="3"/><circle cx={markerX} cy={markerY} r="7" fill="var(--tk-sim-warm)"/><text x="65" y="35">PAIR ENERGY U / ε</text><text x="505" y="283">SEPARATION r / σ →</text></svg><p>U/ε = 4[(σ/r)¹² − (σ/r)⁶]. σ and ε set length and energy scales. The marker follows your slider; the force changes sign at r/σ = 2¹⁄⁶ ≈ 1.122. The curve is clipped above 3 for readability.</p><p>This pair potential illustrates an energy barrier. It does not solve electron states, derive Pauli exclusion, or model a hand or a wall quantitatively. The ordered dots, cloud shapes, sizes, and motion are schematic. Real atoms vibrate even when you pause this picture.</p></details>
 <p className="atlas-note">Ordinary bodies cannot pass intact through one another at everyday energies. Materials can nevertheless break, dissolve, diffuse, or react. Microscopic tunneling does not make walking through a wall a practical possibility.</p></div>;
}
type Voice={context:AudioContext;osc:OscillatorNode;gain:GainNode;timer:ReturnType<typeof setTimeout>;phrase:boolean};
export function SoundLab(){
 const [frequency,setFrequency]=useState(220),[richness,setRichness]=useState(.3),[amplitude,setAmplitude]=useState(.35),[vacuum,setVacuum]=useState(false),[audio,setAudio]=useState(false),[error,setError]=useState(''),[phrase,setPhrase]=useState(false);
 const {running,setRunning,phase,setPhase}=useMotion();const voice=useRef<Voice|null>(null),generation=useRef(0);
 const stop=()=>{generation.current++;const v=voice.current;voice.current=null;if(v){clearTimeout(v.timer);v.gain.gain.cancelScheduledValues(v.context.currentTime);v.gain.gain.setTargetAtTime(0,v.context.currentTime,.01);setTimeout(()=>{try{v.osc.stop();}catch{}void v.context.close().catch(()=>{});},60);}setAudio(false);setPhrase(false);};
 useEffect(()=>{const hide=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hide);window.addEventListener('pagehide',stop);return()=>{document.removeEventListener('visibilitychange',hide);window.removeEventListener('pagehide',stop);stop();};},[]);
 useEffect(()=>{const v=voice.current;if(!v)return;if(vacuum){stop();return;}const w=harmonicWeights(richness),imag=new Float32Array([0,...w.map(a=>a/w.reduce((x,y)=>x+y,0))]);v.osc.setPeriodicWave(v.context.createPeriodicWave(new Float32Array(5),imag,{disableNormalization:true}));if(!v.phrase)v.osc.frequency.setTargetAtTime(frequency,v.context.currentTime,.02);v.gain.gain.setTargetAtTime(amplitude*.12,v.context.currentTime,.02);},[frequency,richness,amplitude,vacuum]);
 async function play(isPhrase=false){stop();setError('');const token=generation.current;let context:AudioContext|undefined;
  try{if(!window.AudioContext)throw new Error('Web Audio is not available in this browser.');context=new AudioContext();await context.resume();if(token!==generation.current){await context.close();return;}if(context.state!=='running')throw new Error('Audio could not start. Try pressing Play again.');const osc=context.createOscillator(),gain=context.createGain();const w=harmonicWeights(richness),sum=w.reduce((a,b)=>a+b,0);osc.setPeriodicWave(context.createPeriodicWave(new Float32Array(5),new Float32Array([0,...w.map(a=>a/sum)]),{disableNormalization:true}));const now=context.currentTime;osc.frequency.value=frequency;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(amplitude*.12,now+.03);if(isPhrase){[1,1.25,1.5,2].forEach((ratio,i)=>osc.frequency.setValueAtTime(frequency*ratio,now+i*.8));}osc.connect(gain);gain.connect(context.destination);osc.start();const timer=setTimeout(stop,isPhrase?3200:8000);voice.current={context,osc,gain,timer,phrase:isPhrase};setAudio(true);setPhrase(isPhrase);
  }catch(e){if(context)void context.close().catch(()=>{});if(token===generation.current)setError(e instanceof Error?e.message:'Audio is unavailable. The visual model still works.');}
 }
 const speed=frequency/220,displacement=(x:number)=>vacuum?0:waveValue(phase*speed*2-x/90*speed,richness)*amplitude*22;
 const waveform=Array.from({length:161},(_,i)=>`${i?'L':'M'}${35+i*4.3},${70-waveValue(i/160*Math.PI*6,richness)*amplitude*65}`).join(' ');
 return <div className="sensory-lab" data-testid="sound-lab"><div className="lab-toolbar"><span className="eyebrow">SOUND / FROM SIGNAL TO SENSATION</span><button className="button" onClick={()=>setRunning(!running)}>{running?'Pause animation':'Resume animation'}</button></div>
 <div className="signal-chain"><span>01 · Electrical signal</span><span>02 · Speaker cone</span><span>03 · Air pressure</span><span>04 · Ear & brain</span></div>
 <svg viewBox="0 0 760 150" className="particle-view" role="img" aria-label="An electronic waveform. Harmonics change the shape; amplitude changes its height."><path d="M35 70H725" stroke="var(--tk-sim-grid)"/><path d={waveform} fill="none" stroke="var(--tk-sim-cool)" strokeWidth="3"/><text x="35" y="135">SIGNAL SHAPE · THREE FUNDAMENTAL CYCLES</text></svg>
 <svg viewBox="0 0 760 285" className="particle-view" role="img" aria-label={vacuum?'The speaker moves, but no air carries sound through the vacuum.':'Air molecules oscillate around their starting points while a compression pattern travels right. The highlighted molecule does not travel to the ear.'}>
 <path d={`M25 100L55 80V220L25 200Z`} fill="var(--tk-sim-muted)"/><path d={`M${65+waveValue(phase*speed*2,richness)*amplitude*12} 80V220`} stroke="var(--tk-sim-warm)" strokeWidth="7"/>
 {!vacuum&&Array.from({length:144},(_,i)=>{const x=100+(i%24)*24,y=95+Math.floor(i/24)*22,tracked=i===60;return <g key={i}>{tracked&&<line x1={x} y1={y-15} x2={x} y2={y+15} stroke="var(--tk-sim-warm)" strokeDasharray="3 3"/>}<circle cx={x+displacement(x-65)} cy={y} r={tracked?6:3} fill={tracked?'var(--tk-sim-warm)':'var(--tk-sim-cool)'} opacity={tracked?1:.7}/></g>;})}
 <text x="95" y="35">{vacuum?'VACUUM · NO SOUND TRANSMITTED':'COMPRESSION PATTERN TRAVELS →'}</text><text x="30" y="260">SPEAKER</text><text x="405" y="260">{vacuum?'No medium, no pressure wave':'Gold dot: one tracked molecule'}</text>
 </svg>
 <p className="particle-caption">Gold dot: one tracked molecule · Dashed line: its reference position. Motion is greatly slowed; the animation does not run at audible frequency.</p>
 <div className="sensory-controls"><label>Pitch · {frequency} Hz<input aria-label="Pitch" type="range" min="110" max="660" step="1" value={frequency} disabled={phrase} onChange={e=>setFrequency(+e.target.value)}/></label><label>Harmonics · {Math.round(richness*100)}%<input aria-label="Harmonics" type="range" min="0" max="1" step=".01" value={richness} onChange={e=>setRichness(+e.target.value)}/></label><label>Amplitude · {Math.round(amplitude*100)}%<input aria-label="Amplitude" type="range" min="0" max="1" step=".01" value={amplitude} onChange={e=>setAmplitude(+e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={vacuum} onChange={e=>setVacuum(e.target.checked)}/> Remove air (vacuum)</label></div>
 <div className="audio-actions"><button className="button primary" disabled={vacuum||audio} onClick={()=>void play()}>Play tone · 8 seconds</button><button className="button" disabled={vacuum||audio} onClick={()=>void play(true)}>Play four-note phrase</button><button className="button" disabled={!audio} onClick={stop}>Stop sound</button><button className="button" onClick={()=>{setRunning(false);setPhase(p=>p+Math.PI/8);}}>Advance animation one step</button></div>
 <p role="status" className="audio-status">{error|| (audio?(phrase?'Playing four notes: frequency ratios 1 : 1.25 : 1.5 : 2.':'Playing a synthesized tone. Adjust the controls to hear it change.'):(vacuum?'No transmitted sound in this model. Restore air to listen.':'Sound is off. Press Play to listen; start with a low device volume.'))}</p>
 <div className="lab-readout"><strong>λ ≈ {wavelength(frequency).toFixed(2)} m in air</strong><span>Using 343 m/s near room temperature. Increasing pitch shortens wavelength; it does not increase sound speed in this model.</span></div>
 <details className="model-details"><summary>What you are hearing—and what this picture leaves out</summary><p>The browser synthesizes a fundamental and up to three harmonics. Your device converts samples into an electrical signal; a speaker turns it into mechanical motion. Changing harmonics changes timbre. The four-note phrase changes frequency over time using simple ratios; it is one possible musical pattern, not a universal musical scale.</p><p>In air, molecules (mainly nitrogen and oxygen) transfer energy through collective pressure fluctuations. Their real motion also includes much faster random thermal motion, omitted here. The organized rows, particle sizes, and displacements are exaggerated; animation time is greatly slowed and not synchronized to audible cycles.</p><p>Your eardrum and middle-ear bones transmit vibration to the cochlea. Hair cells convert mechanical motion into signals carried by nerves. Your brain processes pitch, rhythm, and timbre. You experience this collective process, not individual atoms. A screen cannot make you directly feel atomic motion.</p><p>Vacuum silences the transmitted audio in this teaching model. Electromagnetic signals can cross a vacuum, but a listener still needs a local transducer and a medium to hear ordinary sound. The gain control is not a calibrated sound-pressure or safety meter.</p></details></div>;
}

