import { useMemo, useState } from 'react';
import { runCircuit, probabilities, concurrence, measure, sampleShots, type Gate, type State } from '../lib/quantum';
const labels=['00','01','10','11'];
const presets: {name:string;gates:Gate[];note:string}[]=[
 {name:'Superposition',gates:[{kind:'H',target:0}],note:'H on q0 creates two amplitudes. Measuring gives 00 or 10 with equal probability.'},
 {name:'Interference',gates:[{kind:'H',target:0},{kind:'Z',target:0},{kind:'H',target:0}],note:'Inspect step 2: Z changes the relative phase, not the probabilities. The final H turns that phase difference into a certain 10 outcome.'},
 {name:'Bell pair',gates:[{kind:'H',target:0},{kind:'CNOT',target:1}],note:'Both qubits are individually uncertain, but the pair gives only 00 or 11. This pure state is entangled.'},
 {name:'Independent pair',gates:[{kind:'H',target:0},{kind:'H',target:1}],note:'All four outcomes are equally likely. Each qubit has its own superposition; the pair is not entangled.'}
];
function amplitude(a:{re:number;im:number}){const r=Math.abs(a.re)<1e-9?0:a.re,i=Math.abs(a.im)<1e-9?0:a.im;return i===0?r.toFixed(3):`${r.toFixed(3)} ${i<0?'−':'+'} ${Math.abs(i).toFixed(3)}i`;}
export default function QuantumCircuit(){
 const [gates,setGates]=useState<Gate[]>(presets[2].gates),[step,setStep]=useState(2),[target,setTarget]=useState<0|1>(0);
 const [note,setNote]=useState(presets[2].note),[collapsed,setCollapsed]=useState<State|null>(null),[outcome,setOutcome]=useState<number|null>(null),[shots,setShots]=useState<number[]|null>(null);
 const prepared=useMemo(()=>runCircuit(gates,step),[gates,step]);const state=collapsed??prepared;const probs=probabilities(state),entanglement=concurrence(state);
 const clearResults=()=>{setCollapsed(null);setOutcome(null);setShots(null);};
 function load(next:Gate[],message:string){setGates(next);setStep(next.length);clearResults();setNote(message);}
 function append(kind:Gate['kind']){if(gates.length>=12)return;load([...gates,{kind,target}],kind==='CNOT'?`CNOT flips q${target} only when q${1-target} is 1.`:`${kind} applied to q${target}. Compare the amplitudes and probabilities.`);}
 return <div className="quantum-lab">
  <div className="quantum-top"><div><span className="eyebrow">LIVE CIRCUIT · 2 QUBITS</span><h3>A small circuit. A different set of rules.</h3></div><span className="model-tag">Ideal simulator</span></div>
  <div className="quantum-presets" aria-label="Example circuits">{presets.map(p=><button key={p.name} onClick={()=>load(p.gates,p.note)}>{p.name}</button>)}<button onClick={()=>load([],'Begin at 00. Add a gate, then inspect what changes.')}>Clear circuit</button></div>
  <div className="circuit-scroll" tabIndex={0} role="region" aria-label="Circuit diagram, read left to right"><div className="circuit-wires" style={{minWidth:Math.max(270,90+gates.length*55)}}>{[0,1].map(q=><div className="circuit-wire" key={q}><span className="wire-label">q{q} |0⟩</span>{gates.map((g,i)=><span className={`gate-cell ${i<step?'applied':'pending'} ${g.kind==='CNOT'?'connected':''}`} key={i}><span className={g.kind==='CNOT'?(g.target===q?'gate-box':'control-dot'):g.target===q?'gate-box':'wire-pass'}>{g.kind==='CNOT'?(g.target===q?'⊕':'●'):g.target===q?g.kind:'─'}</span></span>)}{gates.length===0&&<span className="wire-empty">Add your first gate</span>}</div>)}</div></div>
  <div className="gate-tools"><label>Apply to <select aria-label="Target qubit" value={target} onChange={e=>setTarget(Number(e.target.value) as 0|1)}><option value={0}>q0</option><option value={1}>q1</option></select></label><div className="gate-buttons">{(['H','X','Z','S','CNOT'] as const).map(g=><button key={g} disabled={gates.length>=12} onClick={()=>append(g)} title={{H:'Hadamard: mix amplitudes',X:'Bit flip',Z:'Phase flip',S:'Quarter-turn phase',CNOT:`Controlled X: control q${1-target}, target q${target}`}[g]}>Add {g}</button>)}</div><button disabled={!gates.length} onClick={()=>load(gates.slice(0,-1),'Last gate removed; the edited circuit is prepared again from 00.')}>Undo</button></div>
  <label className="step-control">Inspect after gate <strong>{step} / {gates.length}</strong><input aria-label="Inspect circuit step" type="range" min={0} max={gates.length||1} value={step} disabled={!gates.length} onChange={e=>{setStep(Number(e.target.value));clearResults();}}/></label>
  <p className="quantum-note" role="status">{outcome===null?note:`Measured ${labels[outcome]}. The displayed state has collapsed. Measuring it again gives the same result; re-prepare to repeat the experiment.`}</p>
  <div className="quantum-results"><div><p className="eyebrow">{collapsed?'AFTER MEASUREMENT':'MEASUREMENT PROBABILITIES'}</p><div className="probability-chart">{probs.map((p,i)=><div className="probability-row" key={i} data-outcome={labels[i]}><span>|{labels[i]}⟩</span><div className="probability-track"><div style={{width:`${p*100}%`}}/></div><strong>{(p*100).toFixed(1)}%</strong></div>)}</div><p className="quantum-caption">Basis order: |q0 q1⟩. Bars show exact model probabilities.</p></div><div className="state-readout"><p className="eyebrow">AMPLITUDES · a + bi</p>{state.map((a,i)=><div key={i}><span>|{labels[i]}⟩</span><code>{amplitude(a)}</code></div>)}<p>Probability = |amplitude|². A minus sign or complex phase can change later interference.</p></div></div>
  <div className="entanglement-readout"><span>Entanglement (pure-state concurrence)</span><strong>{entanglement.toFixed(2)} / 1</strong><span>{entanglement<1e-8?'Separable state':entanglement>.999?'Maximally entangled':'Entangled state'}</span></div>
  <div className="quantum-actions"><button className="button primary" onClick={()=>{const result=measure(state);setCollapsed(result.state);setOutcome(result.outcome);setShots(null);}}>Measure once</button><button className="button secondary" disabled={!!collapsed} onClick={()=>setShots(sampleShots(prepared))}>Run 1,000 shots</button><button onClick={clearResults}>Re-prepare circuit</button></div>
  {shots&&<div className="shot-results" role="status"><strong>1,000 fresh preparations</strong><div>{shots.map((n,i)=><span key={i}>|{labels[i]}⟩ <b>{n}</b></span>)}</div><p>Each shot starts with the inspected circuit state. Counts fluctuate around the exact probabilities; the preview is unchanged.</p></div>}
  <details className="quantum-help"><summary>Gate guide & model limits</summary><dl><dt>H · Hadamard</dt><dd>Mixes amplitudes. H followed by H returns the starting state.</dd><dt>X · Bit flip</dt><dd>Swaps the 0 and 1 amplitudes on the selected qubit.</dd><dt>Z · Phase flip</dt><dd>Multiplies the selected qubit’s 1 component by −1.</dd><dt>S · Phase gate</dt><dd>Multiplies the 1 component by i, a quarter-turn of phase.</dd><dt>CNOT · Controlled X</dt><dd>The other qubit controls a flip of the selected target. It can entangle a suitable input; it does not entangle every input.</dd></dl><p>A classical, noiseless state-vector simulation with two qubits and at most 12 gates. Measurements use browser pseudorandom sampling in the computational basis. Editing or inspecting a circuit re-prepares it from 00. There is no hardware connection, error correction, or factoring algorithm here. Concurrence applies to the pure states displayed, not arbitrary mixed states.</p></details>
 </div>;
}
