import type { SimDef } from '../kernel/types';
const params={speed:{label:'Rotation frequency',min:0,max:2,step:.1,value:.5,unit:'Hz'},turns:{label:'Coil turns',min:1,max:20,step:1,value:8},field:{label:'Magnetic field',min:.1,max:2,step:.1,value:.5,unit:'T'}};
type State={phase:number};
export const inducedEmf=(phase:number,p:{speed:number;turns:number;field:number})=>p.turns*p.field*.1*2*Math.PI*p.speed*Math.sin(phase);
export default {
 id:'induction',title:'A rotating coil makes an alternating voltage',mode:'sandbox',params,init:()=>({phase:0}),step(s,dt,p){s.phase=(s.phase+2*Math.PI*p.speed*dt)%(2*Math.PI);},
 draw({ctx:c,width:w,height:h,palette:p},s,v){c.fillStyle=p.bg;c.fillRect(0,0,w,h);const k=Math.min(w/640,h/360);c.strokeStyle=p.grid;for(let y=.2;y<.8;y+=.12){c.beginPath();c.moveTo(w*.08,h*y);c.lineTo(w*.57,h*y);c.stroke();c.fillStyle=p.muted;c.font=`${16*k}px monospace`;c.fillText('→',w*.5,h*y+5*k);}c.save();c.translate(w*.32,h*.5);c.strokeStyle=p.warm;c.lineWidth=3*k;const rx=Math.max(4*k,Math.abs(Math.sin(s.phase))*w*.13);c.beginPath();c.ellipse(0,0,rx,h*.25,0,0,Math.PI*2);c.stroke();c.restore();const cx=w*.78,cy=h*.5,r=w*.14;c.strokeStyle=p.grid;c.lineWidth=2*k;c.beginPath();c.arc(cx,cy,r,Math.PI,2*Math.PI);c.stroke();const normalized=Math.sin(s.phase)*(v.speed/2)*(v.turns/20)*(v.field/2);c.strokeStyle=p.cool;c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+Math.sin(normalized*Math.PI/2)*r,cy-Math.cos(normalized*Math.PI/2)*r);c.stroke();c.fillStyle=p.ink;c.font=`${14*k}px monospace`;c.textAlign='center';c.fillText(`${inducedEmf(s.phase,v).toFixed(2)} V`,cx,cy+34*k);c.fillStyle=p.muted;c.font=`${11*k}px monospace`;c.fillText('Uniform field → rotating coil',w*.31,h*.9);c.fillText('Induced EMF',cx,h*.77);c.textAlign='left';},
 readouts:(s,p)=>[{label:'Induced voltage',value:`${inducedEmf(s.phase,p).toFixed(2)} V`,tone:'cool'},{label:'Flux per turn',value:`${(p.field*.1*Math.cos(s.phase)).toFixed(3)} Wb`},{label:'Loop area',value:'0.10 m²'}],equation:'\\mathcal{E}=-N\\frac{d\\Phi_B}{dt}',notice:'Stop rotation and voltage drops to zero, even when magnetic flux remains. This ideal rotating-loop model illustrates Faraday’s law; it is not a reconstruction of his original apparatus. Resistance and back reaction are omitted.'
} satisfies SimDef<State,typeof params>;
