import type { SimDef } from '../kernel/types';
const params={frequency:{label:'Light frequency',min:300,max:1200,step:10,value:700,unit:'THz'},intensity:{label:'Photon flux',min:0,max:100,step:5,value:50,unit:'%'},work:{label:'Work function',min:1.5,max:5,step:.1,value:2.3,unit:'eV'}};
type State={t:number};
export const photonEnergy=(frequency:number)=>4.135667696e-3*frequency;
export default {
 id:'photoelectric',title:'Light quanta and the emission threshold',mode:'sandbox',params,init:()=>({t:0}),step(s,dt){s.t+=dt;},
 draw({ctx:c,width:w,height:h,palette:p},s,v){c.fillStyle=p.bg;c.fillRect(0,0,w,h);const k=Math.min(w/640,h/360), energy=photonEnergy(v.frequency)-v.work; c.fillStyle=p.muted;c.fillRect(w*.4,h*.2,8*k,h*.58);c.fillStyle=p.ink;c.font=`${13*k}px monospace`;c.fillText('LIGHT',w*.08,h*.14);c.fillText('METAL',w*.35,h*.9);c.fillText('ELECTRONS',w*.64,h*.14);for(let i=0;i<Math.ceil(v.intensity/5);i++){const phase=(s.t*.65+i*.163)%1,y=h*(.27+(i%6)*.085);c.strokeStyle=p.warm;c.lineWidth=2*k;c.beginPath();c.moveTo(w*(.07+phase*.3),y);c.lineTo(w*(.07+phase*.3)+10*k,y);c.stroke();if(energy>0){const x=w*(.43+((s.t*Math.sqrt(energy)*.3+i*.163)%1)*.48);c.fillStyle=p.cool;c.beginPath();c.arc(x,y,3*k,0,Math.PI*2);c.fill();}}c.fillStyle=energy>0?p.good:p.hot;c.font=`${14*k}px monospace`;c.fillText(v.intensity===0?'LIGHT OFF':energy>0?'ELECTRONS EMITTED':'BELOW THRESHOLD',w*.51,h*.78);},
 readouts:(_,v)=>[{label:'Photon energy',value:`${photonEnergy(v.frequency).toFixed(2)} eV`,tone:'warm'},{label:'Maximum electron energy',value:photonEnergy(v.frequency)>v.work?`${(photonEnergy(v.frequency)-v.work).toFixed(2)} eV`:'No emission',tone:'cool'},{label:'Threshold frequency',value:`${(v.work/4.135667696e-3).toFixed(0)} THz`}],equation:'K_{\\max}=hf-\\phi',notice:'Raise photon flux below the threshold: there is still no emission. Raise frequency instead. The energy readout is the maximum available energy; particle counts and travel speed are illustrative, with no collecting voltage or energy distribution modelled.'
} satisfies SimDef<State,typeof params>;
